www/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/', 'SeriesController@index')->name('series.index');

Route::get('series/{seriesSlug}/episodes/{episodeSlug}', 'SeriesEpisodesController@show')->name('seriesEpisodes.show');

Route::post('stripe/webhook', 'WebhookController@handleWebhook')->name('webhook');

Route::middleware('auth')->group(function () {
    Route::get('/account', 'AccountsController@index')->name('accounts.index')->middleware('auth');
    Route::post('/account', 'AccountsController@store')->name('accounts.store')->middleware('auth');

    Route::get('/payouts', 'PayoutsController@index')->name('payouts.index')
        ->middleware('providersOnly');

    Route::get('/subscriptions/renew', 'SubscriptionsController@create')->name('subscriptions.create')
        ->middleware('customersOnly');

    Route::get('/subscriptions/delete', 'SubscriptionsController@destroy')->name('subscriptions.destroy')
        ->middleware('customersOnly');
});

www/app/Models/Series.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Series extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'cover_image',
        'description',
        'external_slug',
        'name',
        'provider_id',
        'slug',
    ];

    /*
     * Accessors
     */

    public function getRouteUrlAttribute()
    {
        $this->loadMissing('firstEpisode');

        return route('seriesEpisodes.show', [
            'seriesSlug' => $this->slug,
            'episodeSlug' => $this->firstEpisode->slug,
        ]);
    }

    public function getDurationAttribute()
    {
        return $this->episodes()->sum('duration');
    }

    /*
     * Scopes
     */

    public function scopeOrder($q, $params)
    {
        $params['order'] = $params['order'] ?? 'name';

        switch ($params['order']) {
            case 'recent':
                $q->orderBy('updated_at', 'desc');
                break;

            case 'name':
                $q->orderBy('name', 'asc');
                break;
        }
    }

    public function scopeSearch($q, $params)
    {
        $params = array_filter($params);

        if ( count($params) == 0 ) {
            return $q;
        }

        foreach ($params as $param => $value){
            switch ($param) {
                case 'providers':
                    $q->whereHas('provider', function ($q) use ($value) {
                        $q->whereIn('name', $value);
                    });
                    break;

                case 'text':
                    $q->where('name', 'like', '%' . $value .'%');
                    break;

                case 'tags':
                    $q->whereHas('tags', function ($q) use ($value) {
                        $q->whereIn('name', $value);
                    });
                    break;
            }
        }
    }

    /*
     * Relationships
     */

    public function firstEpisode()
    {
        return $this->hasOne(Episode::class)->oldest('id');
    }

    public function episodes()
    {
        return $this->hasMany(Episode::class);
    }

    public function provider()
    {
        return $this->belongsTo(Provider::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'series_tags');
    }
}

www/app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'colour',
        'name',
        'slug',
    ];

    public $timestamps = false;

    public function getUrlAttribute()
    {
        return route('series.index', ['tags[]' => $this->name]);
    }
}

www/app/Http/Controllers/SeriesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Provider;
use App\Models\Series;
use App\Models\Tag;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;

class SeriesController extends Controller
{
    /**
     * Show all series
     *
     * @param Request $request
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request) : Renderable
    {
        $series = Series::with('provider', 'tags', 'firstEpisode')
            ->search($request->all())
            ->order($request->all())
            ->paginate();

        $providers = Provider::all();
        $tags = Tag::all();

        return view('series.index', compact('providers', 'series', 'tags'));
    }
}

www/resources/views/series/index.blade.php
@extends('layouts.app')

@section('content')
    <form class="form-inline" action="" method="get">
        {{--<label for="providers">Providers</label>--}}
        {{--<select id="providers" class="mb-2 mr-sm-2" name="providers[]" multiple>--}}
            {{--@foreach($providers as $provider)--}}
                {{--<option value="{{ $provider->slug }}">{{ $provider->name }}</option>--}}
            {{--@endforeach--}}
        {{--</select> <br/>--}}

        <label for="text" class="mb-2 mr-sm-2">Text</label>
        <input id="text" class="mb-2 mr-sm-2" type="text" name="text" placeholder="search Title / Description"/><br/>

        {{--<label>Tags</label>--}}
        {{--<select name="tags[]" class="mb-2 mr-sm-2" multiple>--}}
            {{--@foreach($tags as $tag)--}}
                {{--<option value="{{ $tag->name }}">{{ $tag->name }}</option>--}}
            {{--@endforeach--}}
        {{--</select> <br/>--}}

        <input type="submit" class="btn btn-primary mb-2" name="search">
    </form>

        <div class="row text-center">
        @foreach($series as $aSeries)
            <div class="col-md-3">
                <div class="card mb-5 text-center">
                    <div class="card-header">
                        <h5 class="card-title">{{ $aSeries->name }}</h5>
                    </div>
                    <div class="card-body">
                        <div>
                            <a href="{{ $aSeries->route_url }}" class="btn btn-primary">Watch</a>
                        </div>

                        <div>
                            Duration: {{ formatDuration($aSeries->duration) }}
                        </div>

                        <div>
                            @foreach($aSeries->tags as $tag)
                                <a class="btn btn-secondary bg-layout" href="{{ $tag->url }}">{{ $tag->name }}</a>
                            @endforeach
                        </div>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">{{ $aSeries->updated_at->diffForHumans() }}</small>
                    </div>
                </div>
            </div>
        @endforeach
        </div>

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {{ $series->links() }}
            </div>
        </div>
    </div>

@endsection

www/resources/views/series/show.blade.php
@extends('layouts.app')

@section('content')
    {{ $series->name }} <br/>
    {{ $series->description }}<br/>

    <br/>
    <br/>

    @foreach($episodes as $episode)
        {{ $episode->name }}<br/>
        {{ $episode->description }}<br/>
        {{ $episode->duration }}<br/>

        <br/>
        <br/>
    @endforeach
@endsection